spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/bank_db
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

security:
  jwt:
    token:
      secret: 8d4fed75477d160c393db8a22edce23a5ae7971b4533077d89ac0016dd92c879d21791073310294924cb896443a8214cfdc129baa42af8b3030a397382a93532

accountProcessing:
  initialDelay: 30000
  fixedDelay: 30000

redis:
  host: localhost
  port: 6340
