version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_db

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6340:6379